### ISSUE TITLE
Dose HDMI work?

### ISSUE THREAD

**Issue by qykingle** [Errrneist/Hackintosh-Aero-15W#3]
I can't use HDMI

**Comment by wu-hongjun** [comment]
I have no idea...I do not have an external monitor...

**Comment by wu-hongjun** [comment]
After I borrowed my friend's monitor, unfortunately, it does not work. I don't have a monitor with me so I cannot tweak it, but maybe you can make it straight? When you solved this problem you are welcome to submit a pull request!
