### ISSUE TITLE
Apple ALC not working in 10.13.5

### ISSUE THREAD

**Issue by ltanedo** [Errrneist/Hackintosh-Aero-15W#4]
During post-install, when replacing EFI folder with EFI folder from repository, sound doesn't work.  I've also tried installing all of the kexts manually.   I'm not sure if I'm missing any steps.  Any point in the right direction would be greatly appreciated, thanks.

**Comment by wu-hongjun** [comment]
Yes, I also experience this on my machine. I uploaded a new release replacing the AppleALC with VoodooHDA2.9.1 That solves half of the problem but still, temporary solution. Stay tuned!

**Comment by wu-hongjun** [comment]
I changed AppleALC back to VoodooHDA. AppleALC is becoming very unstable, so I suggest just use VoodooHDA for now. Maybe it will get better when Mojave comes out. [Release.](https://github.com/Errrneist/Hackintosh-Aero-15W/releases/tag/v10.13.6-fix1)
