### ISSUE TITLE
AppleBusPowerController

### ISSUE THREAD

**Issue by Kingtous** [Errrneist/Hackintosh-Aero-15W#7]
I'm using Aero 15w and have burned a bootable usb drive(macOS 10.14.0 included).
But When I tried to boot my computer, it stopped with an prohibit symbol and cannot enter the installation. 
This is the latest message showed in Verbose Mode:
> AppleBusPowerController ... Power Supply Unavaliable..

I got a little confused and dont know how could I solve this problem.

**Comment by wu-hongjun** [comment]
I have no idea. I don’t have my laptop with me since it’s been sold for over half a year, but you can always ask this on TonyMacX86. People there would love to help you on this error message.
